package backend;

class Keybinds
{
    public static function fill():Array<Array<Dynamic>>
    {
        return [
			[
				ClientPrefs.keyBinds.get('note_one1').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_two1').copy(),
				ClientPrefs.keyBinds.get('note_two2').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_three1').copy(),
				ClientPrefs.keyBinds.get('note_three2').copy(),
				ClientPrefs.keyBinds.get('note_three3').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_left').copy(),	//SWAGGER SOULS??
				ClientPrefs.keyBinds.get('note_down').copy(),
				ClientPrefs.keyBinds.get('note_up').copy(),
				ClientPrefs.keyBinds.get('note_right').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_five1').copy(),
				ClientPrefs.keyBinds.get('note_five2').copy(),
				ClientPrefs.keyBinds.get('note_five3').copy(),
				ClientPrefs.keyBinds.get('note_five4').copy(),
				ClientPrefs.keyBinds.get('note_five5').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_six1').copy(),
				ClientPrefs.keyBinds.get('note_six2').copy(),
				ClientPrefs.keyBinds.get('note_six3').copy(),
				ClientPrefs.keyBinds.get('note_six4').copy(),
				ClientPrefs.keyBinds.get('note_six5').copy(),
				ClientPrefs.keyBinds.get('note_six6').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_seven1').copy(),
				ClientPrefs.keyBinds.get('note_seven2').copy(),
				ClientPrefs.keyBinds.get('note_seven3').copy(),
				ClientPrefs.keyBinds.get('note_seven4').copy(),
				ClientPrefs.keyBinds.get('note_seven5').copy(),
				ClientPrefs.keyBinds.get('note_seven6').copy(),
				ClientPrefs.keyBinds.get('note_seven7').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_eight1').copy(),
				ClientPrefs.keyBinds.get('note_eight2').copy(),
				ClientPrefs.keyBinds.get('note_eight3').copy(),
				ClientPrefs.keyBinds.get('note_eight4').copy(),
				ClientPrefs.keyBinds.get('note_eight5').copy(),
				ClientPrefs.keyBinds.get('note_eight6').copy(),
				ClientPrefs.keyBinds.get('note_eight7').copy(),
				ClientPrefs.keyBinds.get('note_eight8').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_nine1').copy(),
				ClientPrefs.keyBinds.get('note_nine2').copy(),
				ClientPrefs.keyBinds.get('note_nine3').copy(),
				ClientPrefs.keyBinds.get('note_nine4').copy(),
				ClientPrefs.keyBinds.get('note_nine5').copy(),
				ClientPrefs.keyBinds.get('note_nine6').copy(),
				ClientPrefs.keyBinds.get('note_nine7').copy(),
				ClientPrefs.keyBinds.get('note_nine8').copy(),
				ClientPrefs.keyBinds.get('note_nine9').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_ten1').copy(),
				ClientPrefs.keyBinds.get('note_ten2').copy(),
				ClientPrefs.keyBinds.get('note_ten3').copy(),
				ClientPrefs.keyBinds.get('note_ten4').copy(),
				ClientPrefs.keyBinds.get('note_ten5').copy(),
				ClientPrefs.keyBinds.get('note_ten6').copy(),
				ClientPrefs.keyBinds.get('note_ten7').copy(),
				ClientPrefs.keyBinds.get('note_ten8').copy(),
				ClientPrefs.keyBinds.get('note_ten9').copy(),
				ClientPrefs.keyBinds.get('note_ten10').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_elev1').copy(),
				ClientPrefs.keyBinds.get('note_elev2').copy(),
				ClientPrefs.keyBinds.get('note_elev3').copy(),
				ClientPrefs.keyBinds.get('note_elev4').copy(),
				ClientPrefs.keyBinds.get('note_elev5').copy(),
				ClientPrefs.keyBinds.get('note_elev6').copy(),
				ClientPrefs.keyBinds.get('note_elev7').copy(),
				ClientPrefs.keyBinds.get('note_elev8').copy(),
				ClientPrefs.keyBinds.get('note_elev9').copy(),
				ClientPrefs.keyBinds.get('note_elev10').copy(),
				ClientPrefs.keyBinds.get('note_elev11').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_twel1').copy(),
				ClientPrefs.keyBinds.get('note_twel2').copy(),
				ClientPrefs.keyBinds.get('note_twel3').copy(),
				ClientPrefs.keyBinds.get('note_twel4').copy(),
				ClientPrefs.keyBinds.get('note_twel5').copy(),
				ClientPrefs.keyBinds.get('note_twel6').copy(),
				ClientPrefs.keyBinds.get('note_twel7').copy(),
				ClientPrefs.keyBinds.get('note_twel8').copy(),
				ClientPrefs.keyBinds.get('note_twel9').copy(),
				ClientPrefs.keyBinds.get('note_twel10').copy(),
				ClientPrefs.keyBinds.get('note_twel11').copy(),
				ClientPrefs.keyBinds.get('note_twel12').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_thir1').copy(),
				ClientPrefs.keyBinds.get('note_thir2').copy(),
				ClientPrefs.keyBinds.get('note_thir3').copy(),
				ClientPrefs.keyBinds.get('note_thir4').copy(),
				ClientPrefs.keyBinds.get('note_thir5').copy(),
				ClientPrefs.keyBinds.get('note_thir6').copy(),
				ClientPrefs.keyBinds.get('note_thir7').copy(),
				ClientPrefs.keyBinds.get('note_thir8').copy(),
				ClientPrefs.keyBinds.get('note_thir9').copy(),
				ClientPrefs.keyBinds.get('note_thir10').copy(),
				ClientPrefs.keyBinds.get('note_thir11').copy(),
				ClientPrefs.keyBinds.get('note_thir12').copy(),
				ClientPrefs.keyBinds.get('note_thir13').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_fort1').copy(),
				ClientPrefs.keyBinds.get('note_fort2').copy(),
				ClientPrefs.keyBinds.get('note_fort3').copy(),
				ClientPrefs.keyBinds.get('note_fort4').copy(),
				ClientPrefs.keyBinds.get('note_fort5').copy(),
				ClientPrefs.keyBinds.get('note_fort6').copy(),
				ClientPrefs.keyBinds.get('note_fort7').copy(),
				ClientPrefs.keyBinds.get('note_fort8').copy(),
				ClientPrefs.keyBinds.get('note_fort9').copy(),
				ClientPrefs.keyBinds.get('note_fort10').copy(),
				ClientPrefs.keyBinds.get('note_fort11').copy(),
				ClientPrefs.keyBinds.get('note_fort12').copy(),
				ClientPrefs.keyBinds.get('note_fort13').copy(),
				ClientPrefs.keyBinds.get('note_fort14').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_fift1').copy(),
				ClientPrefs.keyBinds.get('note_fift2').copy(),
				ClientPrefs.keyBinds.get('note_fift3').copy(),
				ClientPrefs.keyBinds.get('note_fift4').copy(),
				ClientPrefs.keyBinds.get('note_fift5').copy(),
				ClientPrefs.keyBinds.get('note_fift6').copy(),
				ClientPrefs.keyBinds.get('note_fift7').copy(),
				ClientPrefs.keyBinds.get('note_fift8').copy(),
				ClientPrefs.keyBinds.get('note_fift9').copy(),
				ClientPrefs.keyBinds.get('note_fift10').copy(),
				ClientPrefs.keyBinds.get('note_fift11').copy(),
				ClientPrefs.keyBinds.get('note_fift12').copy(),
				ClientPrefs.keyBinds.get('note_fift13').copy(),
				ClientPrefs.keyBinds.get('note_fift14').copy(),
				ClientPrefs.keyBinds.get('note_fift15').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_sixt1').copy(),
				ClientPrefs.keyBinds.get('note_sixt2').copy(),
				ClientPrefs.keyBinds.get('note_sixt3').copy(),
				ClientPrefs.keyBinds.get('note_sixt4').copy(),
				ClientPrefs.keyBinds.get('note_sixt5').copy(),
				ClientPrefs.keyBinds.get('note_sixt6').copy(),
				ClientPrefs.keyBinds.get('note_sixt7').copy(),
				ClientPrefs.keyBinds.get('note_sixt8').copy(),
				ClientPrefs.keyBinds.get('note_sixt9').copy(),
				ClientPrefs.keyBinds.get('note_sixt10').copy(),
				ClientPrefs.keyBinds.get('note_sixt11').copy(),
				ClientPrefs.keyBinds.get('note_sixt12').copy(),
				ClientPrefs.keyBinds.get('note_sixt13').copy(),
				ClientPrefs.keyBinds.get('note_sixt14').copy(),
				ClientPrefs.keyBinds.get('note_sixt15').copy(),
				ClientPrefs.keyBinds.get('note_sixt16').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_sevt1').copy(),
				ClientPrefs.keyBinds.get('note_sevt2').copy(),
				ClientPrefs.keyBinds.get('note_sevt3').copy(),
				ClientPrefs.keyBinds.get('note_sevt4').copy(),
				ClientPrefs.keyBinds.get('note_sevt5').copy(),
				ClientPrefs.keyBinds.get('note_sevt6').copy(),
				ClientPrefs.keyBinds.get('note_sevt7').copy(),
				ClientPrefs.keyBinds.get('note_sevt8').copy(),
				ClientPrefs.keyBinds.get('note_sevt9').copy(),
				ClientPrefs.keyBinds.get('note_sevt10').copy(),
				ClientPrefs.keyBinds.get('note_sevt11').copy(),
				ClientPrefs.keyBinds.get('note_sevt12').copy(),
				ClientPrefs.keyBinds.get('note_sevt13').copy(),
				ClientPrefs.keyBinds.get('note_sevt14').copy(),
				ClientPrefs.keyBinds.get('note_sevt15').copy(),
				ClientPrefs.keyBinds.get('note_sevt16').copy(),
				ClientPrefs.keyBinds.get('note_sevt17').copy()
			],
			[
				ClientPrefs.keyBinds.get('note_ate1').copy(),
				ClientPrefs.keyBinds.get('note_ate2').copy(),
				ClientPrefs.keyBinds.get('note_ate3').copy(),
				ClientPrefs.keyBinds.get('note_ate4').copy(),
				ClientPrefs.keyBinds.get('note_ate5').copy(),
				ClientPrefs.keyBinds.get('note_ate6').copy(),
				ClientPrefs.keyBinds.get('note_ate7').copy(),
				ClientPrefs.keyBinds.get('note_ate8').copy(),
				ClientPrefs.keyBinds.get('note_ate9').copy(),
				ClientPrefs.keyBinds.get('note_ate10').copy(),
				ClientPrefs.keyBinds.get('note_ate11').copy(),
				ClientPrefs.keyBinds.get('note_ate12').copy(),
				ClientPrefs.keyBinds.get('note_ate13').copy(),
				ClientPrefs.keyBinds.get('note_ate14').copy(),
				ClientPrefs.keyBinds.get('note_ate15').copy(),
				ClientPrefs.keyBinds.get('note_ate16').copy(),
				ClientPrefs.keyBinds.get('note_ate17').copy(),
				ClientPrefs.keyBinds.get('note_ate18').copy(),
			]
		];
    }
}